import os
import sys
import logging
import asyncio
import datetime
import uuid
from pulse.config import get_product_config, pipeline_config, BASE_DIR
from pulse.ingestion.cache import load_normalized_cache
from pulse.ingestion.play_store import fetch_reviews
from pulse.pipeline.clustering import cluster_reviews
from pulse.pipeline.summarizer import generate_pulse_report
from pulse.render.doc_section import build_doc_blocks
from pulse.render.email_teaser import build_email_teaser
from pulse.ledger.store import get_run, save_run, save_delivery
from pulse.ledger.models import RunRecord, DeliveryRecord
from pulse.agent.mcp_client import MCPClient

logger = logging.getLogger("pulse-orchestrator")

async def run_pulse_pipeline(product_name: str, iso_week: str, dry_run: bool = False, force_send: bool = False):
    started_at = datetime.datetime.now().isoformat()
    run_id = f"{product_name}-{iso_week}-{uuid.uuid4().hex[:6]}"
    
    # 1. Check SQLite Run Ledger first for idempotency
    logger.info(f"Checking ledger for completed run for {product_name} on week {iso_week}...")
    existing_run = get_run(product_name, iso_week)
    if existing_run and existing_run["status"] == "completed" and not force_send:
        logger.info(f"Run already completed for {product_name} week {iso_week}. Skipping.")
        return {
            "status": "skipped",
            "message": f"Run already completed for week {iso_week}.",
            "run_id": existing_run["run_id"]
        }

    # Load configurations
    prod_config = get_product_config(product_name)
    if not prod_config:
        raise FileNotFoundError(f"Configuration file for product '{product_name}' not found.")
        
    doc_id = prod_config.get("delivery", {}).get("google_doc_id", "")
    email_recipients = prod_config.get("delivery", {}).get("email", {}).get("recipients", [])
    email_mode = "send" if force_send else prod_config.get("delivery", {}).get("email", {}).get("default_mode", "draft")
    window_weeks = prod_config.get("ingestion", {}).get("window_weeks", 10)
    
    # Initialize pending record
    run_record = RunRecord(
        run_id=run_id,
        product=product_name,
        iso_week=iso_week,
        status="pending",
        review_count=0,
        window_weeks=window_weeks,
        started_at=started_at
    )
    save_run(run_record)

    try:
        # 2. Ingest / Retrieve Reviews
        logger.info("Step 1: Ingesting/retrieving Play Store reviews...")
        reviews_list = load_normalized_cache(product_name, iso_week)
        if not reviews_list:
            logger.info("Cache miss. Scraping fresh reviews from Play Store...")
            reviews_list = fetch_reviews(product_name, prod_config, iso_week)
            
        logger.info(f"Total reviews loaded/retrieved: {len(reviews_list)}")
        run_record.review_count = len(reviews_list)
        
        if len(reviews_list) < prod_config.get("ingestion", {}).get("min_reviews", 20):
            logger.warning("Fewer than minimum required reviews. Aborting analysis.")
            run_record.status = "failed"
            run_record.error_message = f"Insufficient reviews (found {len(reviews_list)}, minimum is 20)."
            run_record.completed_at = datetime.datetime.now().isoformat()
            save_run(run_record)
            return {"status": "failed", "error": run_record.error_message}

        # 3. Clustering
        logger.info("Step 2: Clustering reviews into semantic themes...")
        clustered_data = cluster_reviews(reviews_list)
        
        # 4. LLM Summarization & Quote Validation
        logger.info("Step 3: Generating LLM summaries and validating quotes...")
        max_themes = pipeline_config.get("summarization", {}).get("max_themes", 5)
        themes = generate_pulse_report(clustered_data, reviews_list, max_themes=max_themes)
        logger.info(f"Generated {len(themes)} summarized themes.")

        if not themes:
            raise ValueError("No themes generated by the summarizer pipeline.")

        # 5. Build output document blocks and email teaser
        logger.info("Step 4: Rendering document blocks and email teaser...")
        doc_anchor = f"{prod_config.get('display_name', product_name)} — Weekly Review Pulse — {iso_week}"
        doc_blocks = build_doc_blocks(themes, iso_week, window_weeks)
        
        # Paths to python MCP servers
        python_exe = sys.executable
        docs_mcp_path = os.path.join(BASE_DIR, "mcp-servers", "google-docs-mcp", "server.py")
        gmail_mcp_path = os.path.join(BASE_DIR, "mcp-servers", "gmail-mcp", "server.py")

        doc_url = ""
        heading_id = None
        
        # 6. Delivery: Write to Google Doc via docs-mcp
        if dry_run:
            logger.info("[DRY RUN] Skipping Google Doc writes.")
            doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"
        else:
            logger.info("Step 5: Writing report section to Google Doc via google-docs-mcp...")
            docs_client = MCPClient(python_exe, [docs_mcp_path])
            await docs_client.connect()
            try:
                # 6.1 Check if section already exists in doc
                anchor_check = await docs_client.call_tool("find_section_by_anchor", {
                    "document_id": doc_id,
                    "anchor": doc_anchor
                })
                
                if anchor_check.get("found"):
                    heading_id = anchor_check.get("heading_id")
                    doc_url = f"https://docs.google.com/document/d/{doc_id}/edit#heading=h.{heading_id}"
                    logger.info(f"Dated section heading already exists. Reusing URL: {doc_url}")
                else:
                    # 6.2 Append the section blocks
                    logger.info(f"Appending new section '{doc_anchor}' to Google Doc...")
                    append_res = await docs_client.call_tool("append_section", {
                        "document_id": doc_id,
                        "anchor": doc_anchor,
                        "blocks": doc_blocks
                    })
                    
                    if "error" in append_res:
                        raise RuntimeError(f"google-docs-mcp error: {append_res['error']}")
                        
                    heading_id = append_res.get("heading_id")
                    doc_url = append_res.get("url", f"https://docs.google.com/document/d/{doc_id}/edit")
                    logger.info(f"Successfully appended section. URL: {doc_url}")
                    
                # Save delivery log
                save_delivery(DeliveryRecord(
                    run_id=run_id,
                    channel="google_doc",
                    external_id=str(heading_id or "root"),
                    url=doc_url
                ))
            finally:
                await docs_client.disconnect()

        # 7. Delivery: Send Email Teaser via gmail-mcp
        email_teaser = build_email_teaser(themes, iso_week, doc_url)
        email_idempotency_key = f"{product_name}-{iso_week}-email"
        
        if dry_run:
            logger.info("[DRY RUN] Skipping Gmail delivery.")
        else:
            logger.info(f"Step 6: Delivering email teaser via gmail-mcp (mode: {email_mode})...")
            gmail_client = MCPClient(python_exe, [gmail_mcp_path])
            await gmail_client.connect()
            try:
                # Check idempotency first
                idem_check = await gmail_client.call_tool("check_idempotency", {
                    "idempotency_key": email_idempotency_key
                })
                
                if idem_check.get("already_sent"):
                    logger.info(f"Teaser email already delivered. ID: {idem_check.get('external_id')}")
                else:
                    if email_mode == "send":
                        send_res = await gmail_client.call_tool("send_email", {
                            "to": email_recipients,
                            "subject": email_teaser["subject"],
                            "html_body": email_teaser["html_body"],
                            "text_body": email_teaser["text_body"],
                            "idempotency_key": email_idempotency_key
                        })
                        if "error" in send_res:
                            raise RuntimeError(f"gmail-mcp send error: {send_res['error']}")
                        msg_id = send_res.get("message_id")
                        logger.info(f"Teaser email sent directly. Message ID: {msg_id}")
                        save_delivery(DeliveryRecord(
                            run_id=run_id,
                            channel="gmail",
                            external_id=msg_id,
                            url="",
                            idempotency_key=email_idempotency_key
                        ))
                    else: # draft
                        draft_res = await gmail_client.call_tool("create_draft", {
                            "to": email_recipients,
                            "subject": email_teaser["subject"],
                            "html_body": email_teaser["html_body"],
                            "text_body": email_teaser["text_body"],
                            "idempotency_key": email_idempotency_key
                        })
                        if "error" in draft_res:
                            raise RuntimeError(f"gmail-mcp draft error: {draft_res['error']}")
                        draft_id = draft_res.get("draft_id")
                        logger.info(f"Teaser email draft created in Gmail. Draft ID: {draft_id}")
                        save_delivery(DeliveryRecord(
                            run_id=run_id,
                            channel="gmail",
                            external_id=draft_id,
                            url="",
                            idempotency_key=email_idempotency_key
                        ))
            finally:
                await gmail_client.disconnect()

        # Update run status to complete
        run_record.status = "completed"
        run_record.completed_at = datetime.datetime.now().isoformat()
        save_run(run_record)
        logger.info(f"Orchestration completed successfully for week {iso_week}.")
        
        return {
            "status": "completed",
            "run_id": run_id,
            "reviews_processed": len(reviews_list),
            "doc_url": doc_url
        }

    except Exception as e:
        logger.error(f"Orchestrator failed during run execution: {e}")
        run_record.status = "failed"
        run_record.error_message = str(e)
        run_record.completed_at = datetime.datetime.now().isoformat()
        save_run(run_record)
        return {"status": "failed", "error": str(e)}
