def build_email_teaser(themes: list[dict], iso_week: str, doc_url: str) -> dict:
    """
    Builds the HTML and plain text bodies for the Gmail teaser email.
    """
    subject = f"Groww Weekly Review Pulse — {iso_week}"
    
    # 1. Build bullet list of theme titles
    theme_bullets_html = ""
    theme_bullets_text = ""
    for idx, theme in enumerate(themes[:5]):
        name = theme.get("theme_name", "Theme")
        size = theme.get("cluster_size", 0)
        summary = theme.get("summary", "")
        theme_bullets_html += f"<li><strong>{name}</strong> ({size} reviews) — {summary}</li>"
        theme_bullets_text += f"- {name} ({size} reviews) - {summary}\n"
        
    # 2. Build HTML Body
    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333333;">
        <h2>Groww Play Store Review Pulse - {iso_week}</h2>
        <p>Hi Team,</p>
        <p>Here are the top themes identified from Play Store reviews this week:</p>
        <ul>
          {theme_bullets_html}
        </ul>
        <p style="margin-top: 25px; margin-bottom: 25px;">
          <a href="{doc_url}" style="background-color: #00d09c; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; font-weight: bold;">
            Read Full Report on Google Docs
          </a>
        </p>
        <hr style="border: 0; border-top: 1px solid #eeeeee;" />
        <p style="font-size: 12px; color: #777777;">
          This is an automated report generated by the Review Pulse Agent.<br />
          Full document URL: <a href="{doc_url}">{doc_url}</a>
        </p>
      </body>
    </html>
    """
    
    # 3. Build Plain Text Body
    text_body = f"""
Groww Play Store Review Pulse - {iso_week}

Hi Team,

Here are the top themes identified from Play Store reviews this week:

{theme_bullets_text}
Read the full report on Google Docs:
{doc_url}

--
This is an automated report generated by the Review Pulse Agent.
    """
    
    return {
        "subject": subject,
        "html_body": html_body,
        "text_body": text_body.strip()
    }
